### ISSUE TITLE
Does not compile (with current reflex I suppose) - is this maintained?

### ISSUE THREAD

**Issue by lspitzner** [bennofs/reflex-host#4]

**Comment by bennofs** [comment]
No, I don't really use it myself so it might have bitrotten. If someone wants to get this working again, I'm happy to help out though.

**Comment by lspitzner** [comment]
I am just evaluating reflex for non-web usage. I'll use the existing code as a reference to get some minimal testing done. Will get back to you if I decide to update this codebase.

**Comment by bennofs** [comment]
Closed in #5
